// Generated by scripts/optimize-comic-pages.mjs. Do not edit manually.
export interface ComicChapterDefinition {
  folder: string;
  title: string;
  firstPage: number;
  lastPage: number;
  pageCount: number;
}

export const COMIC_CHAPTERS: readonly ComicChapterDefinition[] = [
  {
    folder: 'chapter1',
    title: 'Chapter 1',
    firstPage: 0,
    lastPage: 31,
    pageCount: 32,
  },
  {
    folder: 'chapter2',
    title: 'Chapter 2',
    firstPage: 0,
    lastPage: 60,
    pageCount: 61,
  },
  {
    folder: 'chapter3',
    title: 'Chapter 3',
    firstPage: 0,
    lastPage: 58,
    pageCount: 59,
  },
];
